"""initial_schema

Revision ID: 0ebec1c4613f
Revises:
Create Date: 2026-03-06 10:35:01.878701

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ebec1c4613f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clients",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("company_name", sa.String(length=255), nullable=False),
        sa.Column("nif", sa.String(length=20), nullable=True),
        sa.Column("contact_email", sa.String(length=255), nullable=True),
        sa.Column("vertical", sa.String(length=100), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("client_id", sa.Uuid(), nullable=False),
        sa.Column("file_name", sa.String(length=500), nullable=False),
        sa.Column("file_hash", sa.String(length=64), nullable=False),
        sa.Column("total_rows", sa.Integer(), nullable=True),
        sa.Column("total_columns", sa.Integer(), nullable=True),
        sa.Column("health_score", sa.Float(), nullable=True),
        sa.Column("completeness_score", sa.Float(), nullable=True),
        sa.Column("consistency_score", sa.Float(), nullable=True),
        sa.Column("uniqueness_score", sa.Float(), nullable=True),
        sa.Column("total_impact_eur", sa.Float(), nullable=True),
        sa.Column("processing_seconds", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audits_client_id"), "audits", ["client_id"], unique=False)
    op.create_index(op.f("ix_audits_file_hash"), "audits", ["file_hash"], unique=True)
    op.create_table(
        "audit_anomalies",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=False),
        sa.Column("anomaly_type", sa.String(length=100), nullable=False),
        sa.Column("value", sa.Float(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=True),
        sa.Column("context", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_column_profiles",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("column_name", sa.String(length=255), nullable=False),
        sa.Column("inferred_type", sa.String(length=50), nullable=True),
        sa.Column("null_pct", sa.Float(), nullable=True),
        sa.Column("unique_count", sa.Integer(), nullable=True),
        sa.Column("format_inconsistencies", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "audit_findings",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_id", sa.Uuid(), nullable=False),
        sa.Column("category", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("estimated_eur_impact", sa.Float(), nullable=True),
        sa.Column("confidence", sa.String(length=20), nullable=True),
        sa.Column("rows_affected", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["audits.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("audit_findings")
    op.drop_table("audit_column_profiles")
    op.drop_table("audit_anomalies")
    op.drop_index(op.f("ix_audits_file_hash"), table_name="audits")
    op.drop_index(op.f("ix_audits_client_id"), table_name="audits")
    op.drop_table("audits")
    op.drop_table("clients")
    # ### end Alembic commands ###
